### Lecture-14 Numpy

<b>The standard Python data types are not very suited for mathematical operations</b>

In [3]:
lst = [1,2,3]
2 * lst

[1, 2, 3, 1, 2, 3]

In [5]:
#2.5 * lst  # TypeError

<b>Numpy for array or matrix like features</b>

In [6]:
import numpy as np
arr = np.array([1,2,3])

In [8]:
print(arr * 2)

[2 4 6]


In [10]:
arr * arr

array([1, 4, 9])

In [11]:
arr ** 2

array([1, 4, 9], dtype=int32)

In [12]:
# dot product of two vectors
arr1 = np.array([1,2])
arr2 = np.array([3, 4])
arr1.dot(arr2)

11

### shape

In [13]:
a = np.array([2, 3, 8])
a.shape

(3,)

In [14]:
b = np.array([
    [2, 3, 8],
    [4, 5, 6],
    ])
b.shape

(2, 3)

### slice

In [15]:
a = np.array([2, 3, 8])
a[1]

3

In [16]:
a[1:]

array([3, 8])

In [17]:
a[:2]

array([2, 3])

In [18]:
b = np.array([
    [2, 3, 8],
    [4, 5, 6],
    ])

In [19]:
b[1]

array([4, 5, 6])

In [20]:
b[1][2]

6

In [21]:
b[1,2]

6

In [22]:
b[:, 0]

array([2, 4])

In [23]:
b[1, :]  # same as b[1]

array([4, 5, 6])

### masking

In [31]:
arr = np.array([9, 5, 8, 89, 120, 340, 225, 9, 8, 500])

# throw away all values above a certain cutoff, say 100
arr[arr < 100]

array([ 9,  5,  8, 89,  9,  8])

In [32]:
# make them zero
arr[arr > 99] = 0

In [33]:
arr

array([ 9,  5,  8, 89,  0,  0,  0,  9,  8,  0])

### Walk Through-1

In [34]:
arr = np.array([230, 10, 284, 39, 76])

#### Use a mask to multiply all values below 100 by 2

In [35]:
arr[arr < 100] = arr[arr < 100] * 2

In [36]:
arr

array([230,  20, 284,  78, 152])

#### Repeat the above step until all values are above 100

### Walk Through-2

<b>1 2 3 <br>
4 5 6</b>

<b>1 2 3 <br>
4 5 6</b>

#### Add these two matrices

#### Subtract 2nd matrix from 1st matrix

#### Multiply these two matrices